#!/bin/bash
set -euo pipefail

PATTERN="$BUILDKITE_PLUGIN_SPELL_CHECK_PATTERN"   

echo "Running a spelling check report on files with pattern ${PATTERN}"  
docker run --rm -v "$PWD:/mnt" --workdir "/mnt" "tmaier/markdown-spellcheck:latest" "--report" "${PATTERN}"



